version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: data_explainer_db
      MYSQL_USER: default_user
      MYSQL_PASSWORD: default_password
    ports:
      - 12000:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    
  fastapi:
    build: 
      context: .
    container_name: fastapi_container
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mysql
    volumes:
      - .:/app
    networks:
      - app_network
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: